-- 테이블 생성
-- 회원정보 테이블
CREATE TABLE TB_MEMBER(
	MEMBER_NO NUMBER PRIMARY KEY,
	MEMBER_ID VARCHAR2(20) UNIQUE,
	MEMBER_PW VARCHAR2(30) NOT NULL,
	MEMBER_NAME VARCHAR2(10) NOT NULL
);


-- 상세정보 메모 적는 테이블
CREATE TABLE TB_MEMO (
   MEMO_NO NUMBER PRIMARY KEY, 
   MEMO_TITLE VARCHAR2(100),
   MEMO_DETAIL VARCHAR2(4000),
   MEMO_DATE DATE DEFAULT SYSDATE,
   MEMO_UPDATE DATE,
   MEMBER_NO NUMBER CONSTRAINT MEMBER_NO_FK 
   REFERENCES TB_MEMBER(MEMBER_NO)
);
--메모번호 / 제목 / 내용 / 작성일 / 수정일 / 회원번호

SELECT * FROM TB_MEMO;
SELECT * FROM TB_MEMBER;

COMMENT ON COLUMN TB_MEMBER.MEMBER_NO IS '회원 번호';
COMMENT ON COLUMN TB_MEMBER.MEMBER_ID IS '아이디';
COMMENT ON COLUMN TB_MEMBER.MEMBER_PW IS '비밀번호';
COMMENT ON COLUMN TB_MEMBER.MEMBER_NAME IS '이름';

COMMENT ON COLUMN TB_MEMO.MEMO_NO IS '메모번호';
COMMENT ON COLUMN TB_MEMO.MEMO_TITLE IS '제목';
COMMENT ON COLUMN TB_MEMO.MEMO_DETAIL IS '내용';
COMMENT ON COLUMN TB_MEMO.MEMO_DATE IS '작성일';
COMMENT ON COLUMN TB_MEMO.MEMO_UPDATE IS '수정일';
COMMENT ON COLUMN TB_MEMO.MEMBER_NO IS '회원번호';

-- 시퀀스 생성
CREATE SEQUENCE SEQ_MEMBER_NO NOCACHE;
CREATE SEQUENCE SEQ_MEMO_NO NOCACHE;

DROP SEQUENCE SEQ_MEMO_NO;
-- 샘플 데이터
INSERT INTO TB_TODO
VALUES(SEQ_TODO_NO.NEXTVAL, '테스트1', '테스트1 입니다.', DEFAULT, DEFAULT);

INSERT INTO TB_TODO
VALUES(SEQ_TODO_NO.NEXTVAL, '테스트2', '테스트2 입니다.', DEFAULT, DEFAULT);

INSERT INTO TB_TODO
VALUES(SEQ_TODO_NO.NEXTVAL, '테스트3', '테스트3 입니다.', DEFAULT, DEFAULT);

INSERT INTO TB_TODO
VALUES(SEQ_TODO_NO.NEXTVAL, '테스트4', '테스트4 입니다.', DEFAULT, DEFAULT);

COMMIT;



SELECT * FROM TB_TODO;

SELECT TODO_NO, TODO_TITLE, TODO_COMPLETE,
TO_CHAR(REG_DATE, 'YYYY-MM-DD HH24:MI:SS') REG_DATE
FROM TB_TODO
ORDER BY TODO_NO ASC;


SELECT COUNT(*)
FROM TB_TODO
WHERE TODO_COMPLETE = 1;

SELECT TODO_NO, TODO_TITLE, TODO_COMPLETE,
TO_CHAR(REG_DATE, 'YYYY-MM-DD HH24:MI:SS') REG_DATE
FROM TB_TODO
WHERE TODO_NO = 1;

DELETE 
FROM TB_TODO 
WHERE TODO_NO = 1;

UPDATE TB_TODO 
SET TODO_NO = 8
WHERE TODO_NO = 1;

COMMIT;