-- 테이블 생성
-- 회원정보 테이블
CREATE TABLE TB_MEMBER(
	MEMBER_NO NUMBER PRIMARY KEY,
	MEMBER_ID VARCHAR2(20) UNIQUE,
	MEMBER_PW VARCHAR2(30) NOT NULL,
	MEMBER_NAME VARCHAR2(10) NOT NULL
);


-- 상세정보 메모 적는 테이블
CREATE TABLE TB_MEMO (
   MEMO_NO NUMBER PRIMARY KEY, 
   MEMO_TITLE VARCHAR2(100),
   MEMO_DETAIL VARCHAR2(4000),
   MEMO_DATE DATE DEFAULT SYSDATE,
   MEMO_UPDATE DATE,
   MEMBER_NO NUMBER CONSTRAINT MEMBER_NO_FK 
   REFERENCES TB_MEMBER(MEMBER_NO)
);
--메모번호 / 제목 / 내용 / 작성일 / 수정일 / 회원번호

SELECT * FROM TB_MEMO;
SELECT * FROM TB_MEMBER;

COMMENT ON COLUMN TB_MEMBER.MEMBER_NO IS '회원 번호';
COMMENT ON COLUMN TB_MEMBER.MEMBER_ID IS '아이디';
COMMENT ON COLUMN TB_MEMBER.MEMBER_PW IS '비밀번호';
COMMENT ON COLUMN TB_MEMBER.MEMBER_NAME IS '이름';

COMMENT ON COLUMN TB_MEMO.MEMO_NO IS '메모번호';
COMMENT ON COLUMN TB_MEMO.MEMO_TITLE IS '제목';
COMMENT ON COLUMN TB_MEMO.MEMO_DETAIL IS '내용';
COMMENT ON COLUMN TB_MEMO.MEMO_DATE IS '작성일';
COMMENT ON COLUMN TB_MEMO.MEMO_UPDATE IS '수정일';
COMMENT ON COLUMN TB_MEMO.MEMBER_NO IS '회원번호';

-- 시퀀스 생성
CREATE SEQUENCE SEQ_MEMBER_NO NOCACHE;
CREATE SEQUENCE SEQ_MEMO_NO NOCACHE;

DROP SEQUENCE SEQ_MEMO_NO;
-- 샘플 데이터


INSERT INTO TB_MEMBER
VALUES(SEQ_MEMBER_NO.NEXTVAL, 'user01', 'pass01', '이서준');

INSERT INTO TB_MEMBER
VALUES(SEQ_MEMBER_NO.NEXTVAL, 'user02', 'pass02', '서민준');

INSERT INTO TB_MEMBER
VALUES(SEQ_MEMBER_NO.NEXTVAL, 'user03', 'pass03', '윤주원');

INSERT INTO TB_MEMBER
VALUES(SEQ_MEMBER_NO.NEXTVAL, 'user04', 'pass04', '한예준');

COMMIT;

INSERT INTO TB_MEMO (MEMO_NO, MEMO_TITLE, MEMO_DETAIL, MEMBER_NO)
VALUES (SEQ_MEMO_NO.NEXTVAL, '회의록 정리', '4월 9일 회의 내용 정리: 프로젝트 일정 조율 및 역할 분담.', 1);

INSERT INTO TB_MEMO (MEMO_NO, MEMO_TITLE, MEMO_DETAIL, MEMBER_NO)
VALUES (SEQ_MEMO_NO.NEXTVAL, '스터디 계획', '이번 주 스터디 목표는 Git 명령어 복습과 실습입니다.', 1);

INSERT INTO TB_MEMO (MEMO_NO, MEMO_TITLE, MEMO_DETAIL, MEMBER_NO)
VALUES (SEQ_MEMO_NO.NEXTVAL, '업무 일지', '오늘은 DB 설계 및 ERD 작성 업무를 진행하였습니다.', 1);

INSERT INTO TB_MEMO (MEMO_NO, MEMO_TITLE, MEMO_DETAIL, MEMBER_NO)
VALUES (SEQ_MEMO_NO.NEXTVAL, '버그 리포트', '로그인 시 비밀번호 확인 오류 발생 - 수정 요청.', 1);

INSERT INTO TB_MEMO (MEMO_NO, MEMO_TITLE, MEMO_DETAIL, MEMBER_NO)
VALUES (SEQ_MEMO_NO.NEXTVAL, '아이디어 메모', '앱에 다크모드 추가 기능 제안. UI 개선도 함께 고려.', 1);


-- 회원정보 2번 메모 목록
INSERT INTO TB_MEMO (MEMO_NO, MEMO_TITLE, MEMO_DETAIL, MEMBER_NO)
VALUES (SEQ_MEMO_NO.NEXTVAL, '프로게이머 일지', '오늘은 페이커와 게임을 하였다 내가 이겼으니 내가 더 잘한다.', 2);

INSERT INTO TB_MEMO (MEMO_NO, MEMO_TITLE, MEMO_DETAIL, MEMBER_NO)
VALUES (SEQ_MEMO_NO.NEXTVAL, '프로게이머의 자세', '항상 자신감있게 공격하자.', 2);

INSERT INTO TB_MEMO (MEMO_NO, MEMO_TITLE, MEMO_DETAIL, MEMBER_NO)
VALUES (SEQ_MEMO_NO.NEXTVAL, '프로게이머 업무', '게임하고 밥먹고 게임하고 밥먹고 게임하고 자고 자유시간', 2);

INSERT INTO TB_MEMO (MEMO_NO, MEMO_TITLE, MEMO_DETAIL, MEMBER_NO)
VALUES (SEQ_MEMO_NO.NEXTVAL, '프로게이머의 애환', '엉덩이와 팔목이 너무 아프다....', 2);

INSERT INTO TB_MEMO (MEMO_NO, MEMO_TITLE, MEMO_DETAIL, MEMBER_NO)
VALUES (SEQ_MEMO_NO.NEXTVAL, '프로게이머 메모', '선배들의 갈굼이 나날이 심해진다. 나의 실력을 질투하는거 같다.', 2);


-- 회원정보 3번 메모 목록
INSERT INTO TB_MEMO (MEMO_NO, MEMO_TITLE, MEMO_DETAIL, MEMBER_NO)
VALUES (SEQ_MEMO_NO.NEXTVAL, '요리사 일지', '오늘은 중화요리를 만들어 보았다. 드럽게 맛없네', 3);

INSERT INTO TB_MEMO (MEMO_NO, MEMO_TITLE, MEMO_DETAIL, MEMBER_NO)
VALUES (SEQ_MEMO_NO.NEXTVAL, '요리사의 자세', '항상 맛있게 요리하려고 노력하자.', 3);

INSERT INTO TB_MEMO (MEMO_NO, MEMO_TITLE, MEMO_DETAIL, MEMBER_NO)
VALUES (SEQ_MEMO_NO.NEXTVAL, '요리사 업무', '씹고 뜯고 맛보고 즐기고', 3);

INSERT INTO TB_MEMO (MEMO_NO, MEMO_TITLE, MEMO_DETAIL, MEMBER_NO)
VALUES (SEQ_MEMO_NO.NEXTVAL, '요리사의 애환', '화상을 너무 많이 입는다 아파용.....', 3);

INSERT INTO TB_MEMO (MEMO_NO, MEMO_TITLE, MEMO_DETAIL, MEMBER_NO)
VALUES (SEQ_MEMO_NO.NEXTVAL, '요리사 메모', '레시피 1. 양파, 파, 마늘을 먼저 볶는다. 2. 고기를 넣고 약한 불로 살짝 익혀준다. 3. 물을 넣고 끓이다가 비법 소스를 넣어준다.', 3);


-- 회원정보 4번 메등록

INSERT INTO TB_MEMO (MEMO_NO, MEMO_TITLE, MEMO_DETAIL, MEMBER_NO)
VALUES (SEQ_MEMO_NO.NEXTVAL, '교사 일지', '오늘은 아이들과 처음 만났다.', 4);

INSERT INTO TB_MEMO (MEMO_NO, MEMO_TITLE, MEMO_DETAIL, MEMBER_NO)
VALUES (SEQ_MEMO_NO.NEXTVAL, '교사의 자세', '내 자식처럼 가르치자.', 4);

INSERT INTO TB_MEMO (MEMO_NO, MEMO_TITLE, MEMO_DETAIL, MEMBER_NO)
VALUES (SEQ_MEMO_NO.NEXTVAL, '교사 업무', '강의 계획 1. 수학 2. 국어 3. 영어 4. 사회', 4);

INSERT INTO TB_MEMO (MEMO_NO, MEMO_TITLE, MEMO_DETAIL, MEMBER_NO)
VALUES (SEQ_MEMO_NO.NEXTVAL, '교사의 애환', '중2병 놈들... 때리고 싶다 근데 신고 당하겠지', 4);

INSERT INTO TB_MEMO (MEMO_NO, MEMO_TITLE, MEMO_DETAIL, MEMBER_NO)
VALUES (SEQ_MEMO_NO.NEXTVAL, '교사 메모', '항상 따뜻하게 가르치려고 노력하는데 마음처럼 되지 않는다.', 4);







SELECT TODO_NO, TODO_TITLE, TODO_COMPLETE,
TO_CHAR(REG_DATE, 'YYYY-MM-DD HH24:MI:SS') REG_DATE
FROM TB_TODO
ORDER BY TODO_NO ASC;


SELECT COUNT(*)
FROM TB_TODO
WHERE TODO_COMPLETE = 1;

SELECT TODO_NO, TODO_TITLE, TODO_COMPLETE,
TO_CHAR(REG_DATE, 'YYYY-MM-DD HH24:MI:SS') REG_DATE
FROM TB_TODO
WHERE TODO_NO = 1;

DELETE 
FROM TB_TODO 
WHERE TODO_NO = 1;

UPDATE TB_TODO 
SET TODO_NO = 8
WHERE TODO_NO = 1;

COMMIT;